name: Setup PsBuilder
description: 'Setup PsBuilder in five seconds, and add it to the PATH'
inputs:
  version:
    - description: 'Version of PsBuilder to install. Set to main for the latest breaking changes, use psbuilder.vereion to set default'
      required: false
branding:
  icon: 'download'
  color: 'blue'
  
      
      
    
jobs:
  setup:
    
    steps:
      
      - name: Check if psbuilder.version exists
        run: |
          if ( ${{ inputs.versionc }} -ne "") { exit }
          cd ./

          $exist = Test-Path ./psbuilder.version
          if (-not $exist) { echo "::error::Could not find psbuilder.version. On non-Windows runners, you may need to checkout the repo before installation. More explanation: https://github.com/marketplace/actions/checkout`nCurrent versions for ${{ runner.os }}: https://github.com/psbuilder/setup/raw/main/versions/${{ runner.os }}.txt" }
          if (-not $exist) { Exit 1 }
          if ($exist) { echo "Found psbuilder.version! Can proceed with installation" }
        shell: pwsh
      - name: Install PsBuilder
        run: |
          $a = (Get-Content ./psbuilder.version | Measure-Object)
          $i = $a.Count


          if ($i -gt 1) { echo "::warning file='psbuilder.version'::Invalid psbuilder.version (expected 1 line, found $i lines). Collecting content of line 1 instead." }
          
          
          if ( ${{ inputs.version ) { $version = ${{ inputs.version } else $version = Get-Content ./psbuilder.version }
          if ($i -gt 1) { $version = Get-Content ./psbuilder.version -First 1 }
          echo "Installing PsBuilder $version from PsBuilder git repo."
          git init psb$version
          cd psb$version
          git branch -m psb$version
          echo "::group::Fetching https://github.com/psbuilder/psbuilder.git"
          git fetch https://github.com/psbuilder/psbuilder.git $version --recurse-submodules --auto-maintenance
          echo "::endgroup::"
        shell: pwsh
      
