name: Setup PsBuilder

on: push

jobs:
  setup:
    runs-on: macos-latest
    steps:
      - name: Check if psbuilder.version exists
        run: |
          cd ./

          $exist = Test-Path ./psbuilder.version
          if (-not $exist) { echo "::error::Could not find psbuilder.version.`nCurrent versions for ${{ runner.os }}: https://github.com/psbuilder/setup/raw/main/versions/${{ runner.os }}.txt" }
          if (-not $exist) { Exit 1 }
          if ($exist) { echo "Found psbuilder.version! Can proceed with installation" }
        shell: pwsh
      - name: Set version
        run: if ($exist) { $version = Get-Content ./psbuilder.version }
        shell: pwsh
      - name: Install PsBuilder
        run: Invoke-WebRequest https://github.com/psbuilder/psbuilder/releases/download/$version/PsBuilder.ps1
        shell: pwsh
      - name: Rename to build
        run: mv "./PsBuilder.ps1" "./build.ps1"
       
