name: Setup PsBuilder

on: push

jobs:
  setup:
    runs-on: macos-latest
    steps:
      - name: Check if psbuilder.version exists
        run: |
          $exist = Test-Path ./psbuilder.version
          if (not $exist -ne true) { echo "::error::Could not find psbuilder.version" }
          if ($exist -ne true) { Exit 1 }
        shell: pwsh
      - name: Set version
        run: if ($exist) { $version = Get-Content ./psbuilder.version }
        shell: pwsh
      - name: Install PsBuilder
        run: Invoke-WebRequest https://github.com/psbuilder/psbuilder/releases/download/$version/PsBuilder.ps1
        shell: pwsh
      - name: Rename to build
        run: mv "./psbuilder.version"
       
