name: Setup PsBuilder

on: push

jobs:
  setup:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check if psbuilder.version exists
        run: |
          cd ./

          $exist = Test-Path ./psbuilder.version
          if (-not $exist) { echo "::error::Could not find psbuilder.version. On non-Windows runners, you may need to checkout the repo before installation. More explanation: https://github.com/marketplace/actions/checkout`nCurrent versions for ${{ runner.os }}: https://github.com/psbuilder/setup/raw/main/versions/${{ runner.os }}.txt" }
          if (-not $exist) { Exit 1 }
          if ($exist) { echo "Found psbuilder.version! Can proceed with installation" }
        shell: pwsh
      - name: Install PsBuilder
        run: |
          $a = (Get-Content ./psbuilder.version | Measure-Object)
          $i = $a.Count


          if ($i -gt 1) { echo "::error::Invalid psbuilder.version. PsBuilder.version must be plain text, not powershell." }
          if ($i -gt 1) { Exit 1 }
          $version = Get-Content ./psbuilder.version
          echo "Installing PsBuilder $version from PsBuilder git repo."
          git init psb$version
          cd psb$version
          git branch -m psb$version
          echo "::group::Fetching https://github.com/psbuilder/psbuilder.git"
          git fetch https://github.com/psbuilder/psbuilder.git $version --progress
          echo "::endgroup::"
        shell: pwsh
      
